name = "twoapi"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "twoapi"

[env.staging]
name = "twoapi-staging"

# 可选的环境变量
[vars]
ENVIRONMENT = "production"